# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dmitriyivkov/CLionProjects/keleidoscope

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dmitriyivkov/CLionProjects/keleidoscope

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dmitriyivkov/CLionProjects/keleidoscope/CMakeFiles /Users/dmitriyivkov/CLionProjects/keleidoscope//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dmitriyivkov/CLionProjects/keleidoscope/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named keleidoscope

# Build rule for target.
keleidoscope: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 keleidoscope
.PHONY : keleidoscope

# fast build rule for target.
keleidoscope/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/build
.PHONY : keleidoscope/fast

ast.o: ast.cpp.o
.PHONY : ast.o

# target to build an object file
ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/ast.cpp.o
.PHONY : ast.cpp.o

ast.i: ast.cpp.i
.PHONY : ast.i

# target to preprocess a source file
ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/ast.cpp.i
.PHONY : ast.cpp.i

ast.s: ast.cpp.s
.PHONY : ast.s

# target to generate assembly for a file
ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/ast.cpp.s
.PHONY : ast.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/main.cpp.s
.PHONY : main.cpp.s

optimizations.o: optimizations.cpp.o
.PHONY : optimizations.o

# target to build an object file
optimizations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/optimizations.cpp.o
.PHONY : optimizations.cpp.o

optimizations.i: optimizations.cpp.i
.PHONY : optimizations.i

# target to preprocess a source file
optimizations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/optimizations.cpp.i
.PHONY : optimizations.cpp.i

optimizations.s: optimizations.cpp.s
.PHONY : optimizations.s

# target to generate assembly for a file
optimizations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/optimizations.cpp.s
.PHONY : optimizations.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/parser.cpp.s
.PHONY : parser.cpp.s

tokens.o: tokens.cpp.o
.PHONY : tokens.o

# target to build an object file
tokens.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/tokens.cpp.o
.PHONY : tokens.cpp.o

tokens.i: tokens.cpp.i
.PHONY : tokens.i

# target to preprocess a source file
tokens.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/tokens.cpp.i
.PHONY : tokens.cpp.i

tokens.s: tokens.cpp.s
.PHONY : tokens.s

# target to generate assembly for a file
tokens.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/keleidoscope.dir/build.make CMakeFiles/keleidoscope.dir/tokens.cpp.s
.PHONY : tokens.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... keleidoscope"
	@echo "... ast.o"
	@echo "... ast.i"
	@echo "... ast.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... optimizations.o"
	@echo "... optimizations.i"
	@echo "... optimizations.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... tokens.o"
	@echo "... tokens.i"
	@echo "... tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

